### ISSUE TITLE
THREE r71 compatibility

### ISSUE THREAD

**Issue by RemusMar** [sunag/sea3d#2]
Very smart 3DS Max exporter.
Excellent compression (a MUST for something in a browser).
Congrats!
Unfortunately is not compatible anymore with the latest THREE releases (r71-r72).

cheers

**Comment by lo-th** [comment]
you can find version here https://github.com/lo-th/root/tree/gh-pages/buildNew

exemple http://jsdo.it/Lo-Th/onUf

**Comment by RemusMar** [comment]
Thank you for the fast response.
However there is something wrong with the 3DS Max Exporter or the THREE.SEA3D importer.
I've tested with 3DS Max 2012 and the 1.6.5 exporter.
1) with NO compression I get excellent results but huge file size
2) with DEFLATED the THREE.SEA3D loader does not work (does not reach the "onComplete" stage)
3) with LZMA I cannot export anything.
![sea3d_lzma](https://cloud.githubusercontent.com/assets/11772787/7584320/58035f98-f8a5-11e4-825b-9e56446d946d.png)

Any fix to get compression for the exported models?
cheers

**Comment by lo-th** [comment]
ok i update with deflated same link

**Comment by RemusMar** [comment]
Well done!
http://necromanthus.com/Test/html5/Lara_sea3d.html 

One more thing (for now):
it would be great a progress callback for the THREE.SEA3D leader.
I've did it for the UTF8Loader sme time ago:
http://necromanthus.com/Test/html5/
I'm sure it can be done for this GREAT loader.

cheers

**Comment by lo-th** [comment]
sure you can add 
loader.onProgress = function( e ) {
   txt_loader.innerHTML = 'Loading '+ name +': '+(e.progress*100).toFixed(0)+'%';
}
loader.onDownloadProgress = function( e ) {
     // start loading
     txt_loader.innerHTML.style.display = 'block';
}

**Comment by RemusMar** [comment]
Thanks for tip.
However all the THREE loaders will be unified.
I will push Ricardo (mrdoob) to do that (LOL).
Please take a look at the source of this page:
http://necromanthus.com/Test/html5/ 
Note that

		var onProgress = function ( data ) {
			var bar = 250;
			if ( data.total ) {
				bar = Math.floor( bar * data.loaded / data.total );
				var loadbar = document.getElementById( 'bar' );
				loadbar.style.width = bar+"px";
			}
		};

So the loader must provide two infos for "data":
data.total and  data.loaded

cheers

**Comment by RemusMar** [comment]
The polling for "e.progress" does not work properly.
Please clear the browser history and try again this link:
http://necromanthus.com/Test/html5/Lara_sea3d.html 
( the size of the loaded file is 1MB)

**Comment by RemusMar** [comment]
I've added the SEA3D version of the "walking girl" to the main benchmark:
http://necromanthus.com/Test/html5/testA_sea3d.html 
As you can see, the preloading part for that girl does not work properly (a single polling for 1MB).

The SEA3D loader should be fixed and unified (data.total and data.loaded, where "data" is "e" in this case).
Please take a look at the updated UTF8Loader (based on the Google WebGL loader):
http://necromanthus.com/Test/html5/JS/UTF8Loader.js 
In the THREE.UTF8Loader.prototype.downloadMesh function, you will find:

callbackProgress( {total: length, loaded: xhr.responseText.length} ); 

That's probably the best approach.
cheers

**Comment by sunag** [comment]
Hi @RemusMar .

Thank you and @lo-th , I will be looking for you. I will respond as soon as possible, still this week.
@lo-th  you have the non min version of its update for r72?

Cheers.

**Comment by lo-th** [comment]
sure https://github.com/lo-th/root/tree/gh-pages/buildNew/loader

**Comment by RemusMar** [comment]
Folks,

That "onProgress" is worthless.
You didn't say anything about "onDownloadProgress", "e.position" and "e.length".
I had to study your sources in order to find them.
Now the preloader works perfect:

http://necromanthus.com/Test/html5/SMC.html 

The SEA3D loader can be unified with the THREE loaders.
Just rename them:
e.position = e.loaded
e.length = e.total

p.s.
Any "hidden" useful infos?
LOL

**Comment by AlexeyGapon** [comment]
So dose it work now? I am trying work with JSON loader + Blend Character but no luck.
Only reason this was not comable woth r71.

**Comment by RemusMar** [comment]
It works, but there is a major issue:
all the imported models have negative scale.
https://github.com/sunag/sea3d/issues/3
