### ISSUE TITLE
Negative scale

### ISSUE THREAD

**Issue by RemusMar** [sunag/sea3d#3]
As I said from the very beginning, SEA3D is an impressive 3DS Max exporter.
And because I didn't like your LightMaps sample, here is a much better one:
http://necromanthus.com/Test/html5/SMC.html 

Now let's come back to the "title" (Negative scale):
All the imported models have flipped faces (inverted normals).
The workaround is very simple:

mesh.scale.multiplyScalar( - 1);

BUT ...
That's problematic for meshes with semi-transparent materials.
The pivots are messed up and that will lead to Z-buffer fightings.
Now I'm not sure where this bug is located: inside of the 3DS Max exporter or inside of the THREE.SEA3D loader.
Please investigate and fix it.

cheers

**Comment by sunag** [comment]
Hi @RemusMar .

Thank you! Have you tried something like this?

```javascript
var loader = new THREE.SEA3D();
loader.invertZ = false;
loader.flipZ = true;
loader.parser = THREE.SEA3D.DEFAULT;
```
More: http://developers.poonya.com/forum/viewtopic.php?f=10&t=154#p724

Cheers

**Comment by RemusMar** [comment]
> loader.invertZ = false;
> loader.flipZ = true;

My workaround ( mesh.scale.multiplyScalar( - 1); ) works in any condition.
Your workaround does not work for skinned meshes:
1) outside of "loader.onComplete"
http://necromanthus.com/Test/html5/Lara_sea3d_bug1.html 
2) inside of "loader.onComplete"
http://necromanthus.com/Test/html5/Lara_sea3d_bug2.html 

But we're talking about workarounds here.
It would be much better a FIX for this issue (buggy 3DS Max exporter ?)

cheers

**Comment by lo-th** [comment]
try 
for animated :   m.scale.set(size, size,-size);
for geometry:    g.applyMatrix(new THREE.Matrix4().makeScale(size,size,-size));
for texture:        t.flipY = false;

**Comment by RemusMar** [comment]
> mesh.scale.set( 1, 1, -1);
> texture.flipY = false;

That workaround works for both static and animated meshes.
But why do we continue to talk about workarounds here?
I'm sure this bug can be fixed!

cheers

**Comment by lo-th** [comment]
it's more complex than you think.
for my use is no problemo

**Comment by RemusMar** [comment]
> it's more complex than you think.

I didn't say it's an easy fix, but any bug has to be fixed.
Don't you agree?


> for my use is no problemo

That "for my use" is irrelevant.
SEA3D has a great potential, but most of the users don't know (or don't like) to use workarounds.
They stay away from buggy apps.
I really like SEA3D and I'm trying to help here.

cheers

**Comment by lo-th** [comment]
yea sure you right
but anyway sea3d is the best exporter for max on webgl

**Comment by sunag** [comment]
Hi @lo-th , @RemusMar.

I did today worker with flipZ which is now a flipX, after various and various tests.
If they want some testing.. still the code is not clean.

I will update and leave only the version with FlipX in midweek!?

https://github.com/sunag/sea3d/tree/master/Labs/Three.JS

Cheers.

**Comment by RemusMar** [comment]
Jean Carlo,

All the imported models have negative scale on all directions (-1,-1,-1).
So the flipX or flipZ workaround is not enough.
The only good workaround is this one:

mesh.scale.multiplyScalar( -1);

But we don't need a workaround here.
We need a FIX.
I'm not sure if the bug is inside of the 3DS Max exporter (that SEA3D Normals modofier applied on all meshes before the file is saved),
or inside of the SEA3DLoader.
Please investigate and fix it.
For the imported models we need the right normals and scale(1,1,1).

cheers

**Comment by RemusMar** [comment]
Your method (flipX or flipZ ) does not work fir this complex scene:
http://necromanthus.com/Test/html5/SMC.html 
You will get wrong UVs and abnormal lighting (even if you flip the faces).
And that's because of the NEGATIVE scale on ALL directions (X, Y & Z).
So only mesh.scale.multiplyScalar( -1); can "fix" this bug.
But this is bad for mesh pivot: all the pivots have to be (0,0,0)
And for materials with semi-transparent textures that's a bad move!
So for the last time:
PLEASE FIX THE NEGATIVE SCALE BUG!

cheers

**Comment by sunag** [comment]
Hi @RemusMar .

>All the imported models have negative scale on all directions (-1,-1,-1).

See the settings in the SEA3D loader of the link, the problem with the skeleton already solved.
http://sunag.github.io/sea3d/labs/
Source in the link above.

All scale is positive.
![larascale](https://cloud.githubusercontent.com/assets/502810/7672441/7f2b28d0-fcc9-11e4-8ff2-3d919a56f260.jpg)

The final revision will finish in the middle of this week as I announced.

>PLEASE FIX THE NEGATIVE SCALE BUG!

Please, be patient. That's what we're doing here.

Cheers.

**Comment by AlexeyGapon** [comment]
Great! Will try today!

**Comment by RemusMar** [comment]
> See the settings in the SEA3D loader of the link, the problem with the skeleton already solved.
> http://sunag.github.io/sea3d/labs/

Jean Carlo,

loader.flipX = true; is a workaround, not a fix.
It works ONLY if all the models have the pivot set to (0,0,0).
Otherwise, the models will get wrong positions on the scene.
Any kind of flipX, flipY, flipZ will mess up the object position on the scene.
Please try by yourself with a simple loaded scene and a few objects.
The real FIX is a single one:
all the imported models must have the right normals and scale(1,1,1).
No flip and no invert.

cheers

**Comment by AlexeyGapon** [comment]
Maybe it will be simpler just add some extra mathematics inside loader withour rewriting it. User will see (1,1,1) and all textures uv will be as usual but inside it will translate into it`s own measures as was loaded.

**Comment by RemusMar** [comment]
> Maybe it will be simpler just add some extra mathematics inside loader withour rewriting it.

I'm not sure where the bug is located (3DS Max exporter or SEA3DLoader).
And Jean Carlo doesn't want to share some light on this subject ...
Anyway, with the current exporter & loader, if you want to let the loaded models untouched and to get the right results:

camera.scale.x = -1; 

But who wants to do that?
If you don't want to mess up the camera, you have to mess up the loaded models:

mesh.scale.multiplyScalar( -1);
mesh.rotation.x = Math.PI;

This is ok for static and animated models.
But if their pivots are not set to (0,0,0), you need to RESTORE their position on the scene!
And that's a nightmare if you have dozens of models.

So all of these are workarounds.
Let's hope Jean Carlo will come with a real FIX.

**Comment by AlexeyGapon** [comment]
I created the character and pleaced him into the game. I used mesh.scale.multiplyScalar( -1); 
and rotation.z = Math.PI, And all my texturez flipped horizontaly. Everything is ok. Then if you want to move your character just calculate it`s position to (0,0,0) then your translation. It`s only 3 lines of code.
But i agree. it would be great to have nice whicj works fine as expected without before testing.

**Comment by RemusMar** [comment]
See this complex benchmark:
http://necromanthus.com/Test/html5/testA_sea3d.html 
JSON, UTF8 and SEA models.
Only the SEA3DLoader is messed up ...

**Comment by AlexeyGapon** [comment]
Do you have skype or something?

**Comment by sunag** [comment]
Hi @RemusMar 

> loader.flipX = true; is a workaround, not a fix.
> Let's hope Jean Carlo will come with a real FIX.

Of course it is a correction, or do you think that every file format should be made for a specifies graphical library? The difference is we let the users interact with the settings here, unlike the others loaders. Get a better look at ColladaLoader.js of Three.js for example, and you will see how many flip corrections exists in it.

Another important thing is respect. Who is the Jean Carlo? Here is Sunag. About getting to know the most SEA3D, this is not the official support forum. I suggest you see the tutorials to better understand the migration to WebGL, SEA3D not born in WebGL and is far from stopping there. So you will be able to see some "hidden" things like onDownloadProgress.

http://developers.poonya.com/forum/viewforum.php?f=11
http://developers.poonya.com/forum/viewforum.php?f=10

> And Jean Carlo doesn't want to share some light on this subject 
Only the SEA3DLoader is messed up ...

SEA3D is open-source because of this you can make anything, improvement and share. Do not expect everything by the collaborators, here no one has an obligation to help anyone and respect begins first of all.

Cheers.

**Comment by RemusMar** [comment]
1) I thought "sunao" = "Jean Carlo Deconto"
https://github.com/mrdoob/three.js/issues/3568 

2) most of the THREE loaders (JSON, OBJ, DAE, UTF8, etc) have been unified.
Please take a look at the source of this benchmark:
http://necromanthus.com/Test/html5/test9_disco.html 
loader.load( url, onComplete, onProgress )
So please rename them in the SEA3DLoader:
onDownloadProgress = onProgress
e.position = e.loaded
e.length = e.total

3) SEA3D has been designed for flash and Away3D.
But flash is dying and here we're talking about JavaScript and WebGL.
So the 3DS Max exporter should be updated and FIXED as well.

4) I told you from the very beginning: SEA3D is a great piece of work!
But there is always room for better and i come here to help.
I don't understand your "respect".issue, but that's your problem not mine.

And finally, I'm waiting for a real fix.
all the best

**Comment by RemusMar** [comment]
And to close your "respect" issue:

I want SEA3D to become the best THREE loader.
I want to promote your work.
Do you have a problem with that?

cheers

**Comment by sunag** [comment]
Hi @RemusMar 

It's nothing personal, it's about being exigent, no one here pays to work, the fact is not to entreat fixes, no one is obliged to anyone, for it the project is open-source, we are doing our best and all do everything possible to improve the SEA3D.

I will this week be announcing the improvements and news.

Cheers.
